// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Actions that can be applied to account rule resource
//  enum AccountRuleAction
//  {
//      ANY = 1,
//      CREATE = 2,
//      CREATE_FOR_OTHER = 3,
//      CREATE_WITH_TASKS = 4,
//      MANAGE = 5,
//      SEND = 6,
//      WITHDRAW = 7,
//      RECEIVE_ISSUANCE = 8,
//      RECEIVE_PAYMENT = 9,
//      RECEIVE_ATOMIC_SWAP = 10,
//      PARTICIPATE = 11,
//      BIND = 12,
//      UPDATE_MAX_ISSUANCE = 13,
//      CHECK = 14,
//      CANCEL = 15,
//      CLOSE = 16,
//      REMOVE = 17,
//      UPDATE_END_TIME = 18,
//      CREATE_FOR_OTHER_WITH_TASKS = 19,
//      REMOVE_FOR_OTHER = 20,
//      EXCHANGE = 21,
//      RECEIVE_REDEMPTION = 22
//  };

//  ===========================================================================
public enum AccountRuleAction: Int32, XDREnum {
  case any = 1
  case create = 2
  case createForOther = 3
  case createWithTasks = 4
  case manage = 5
  case send = 6
  case withdraw = 7
  case receiveIssuance = 8
  case receivePayment = 9
  case receiveAtomicSwap = 10
  case participate = 11
  case bind = 12
  case updateMaxIssuance = 13
  case check = 14
  case cancel = 15
  case close = 16
  case remove = 17
  case updateEndTime = 18
  case createForOtherWithTasks = 19
  case removeForOther = 20
  case exchange = 21
  case receiveRedemption = 22
}
