// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum AssetPolicy
//  {
//  	TRANSFERABLE = 1,
//  	BASE_ASSET = 2,
//  	STATS_QUOTE_ASSET = 4,
//  	WITHDRAWABLE = 8,
//  	ISSUANCE_MANUAL_REVIEW_REQUIRED = 16,
//  	CAN_BE_BASE_IN_ATOMIC_SWAP = 32,
//  	CAN_BE_QUOTE_IN_ATOMIC_SWAP = 64
//  };

//  ===========================================================================
public enum AssetPolicy: Int32, XDREnum {
  case transferable = 1
  case baseAsset = 2
  case statsQuoteAsset = 4
  case withdrawable = 8
  case issuanceManualReviewRequired = 16
  case canBeBaseInAtomicSwap = 32
  case canBeQuoteInAtomicSwap = 64
}
