// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Policies that could be applied to AssetPair entry and define applicable operations for AssetPair
//  enum AssetPairPolicy
//  {
//      //: If not set pair can not be traded on secondary market
//  	TRADEABLE_SECONDARY_MARKET = 1,
//  	//: If set, then prices for new offers must be greater then physical price with correction
//  	PHYSICAL_PRICE_RESTRICTION = 2,
//  	//: if set, then price for new offers must be in interval of (1 ± maxPriceStep)*currentPrice
//  	CURRENT_PRICE_RESTRICTION = 4
//  };

//  ===========================================================================
public enum AssetPairPolicy: Int32, XDREnum {
  case tradeableSecondaryMarket = 1
  case physicalPriceRestriction = 2
  case currentPriceRestriction = 4
}
