// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct ASwapBidExtended
//  {
//      //: ID of the newly created bid as a result of successful review of Create Atomic Swap Bid Request
//      uint64 bidID;
//  
//      //: Reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct ASwapBidExtended: XDREncodable {
  public var bidID: Uint64
  public var ext: ASwapBidExtendedExt

  public init(
      bidID: Uint64,
      ext: ASwapBidExtendedExt) {

    self.bidID = bidID
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.bidID.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum ASwapBidExtendedExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
