// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct AuthCert
//  {
//      Curve25519Public pubkey;
//      uint64 expiration;
//      Signature sig;
//  };

//  ===========================================================================
public struct AuthCert: XDRCodable {
  public var pubkey: Curve25519Public
  public var expiration: Uint64
  public var sig: Signature

  public init(
      pubkey: Curve25519Public,
      expiration: Uint64,
      sig: Signature) {

    self.pubkey = pubkey
    self.expiration = expiration
    self.sig = sig
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.pubkey.toXDR())
    xdr.append(self.expiration.toXDR())
    xdr.append(self.sig.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.pubkey = try Curve25519Public(xdrData: &xdrData)
    self.expiration = try Uint64(xdrData: &xdrData)
    self.sig = try Signature(xdrData: &xdrData)
  }
}
