// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: CancelAtomicSwapAskOp is used to cancel existing atomic swap ask
//  struct CancelAtomicSwapAskOp
//  {
//      //: id of existing atomic swap ask
//      uint64 askID;
//  
//      //: reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct CancelAtomicSwapAskOp: XDRCodable {
  public var askID: Uint64
  public var ext: CancelAtomicSwapAskOpExt

  public init(
      askID: Uint64,
      ext: CancelAtomicSwapAskOpExt) {

    self.askID = askID
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.askID.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.askID = try Uint64(xdrData: &xdrData)
    self.ext = try CancelAtomicSwapAskOpExt(xdrData: &xdrData)
  }

  public enum CancelAtomicSwapAskOpExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion()
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
