// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct CheckSaleClosedResult {
//      //: AccountID of the sale owner
//      AccountID saleOwner;
//      //: Array of the sale participation results 
//      CheckSubSaleClosedResult results<>;
//      //: Reserved for future use
//      union switch (LedgerVersion v)
//      {
//        case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct CheckSaleClosedResult: XDREncodable {
  public var saleOwner: AccountID
  public var results: [CheckSubSaleClosedResult]
  public var ext: CheckSaleClosedResultExt

  public init(
      saleOwner: AccountID,
      results: [CheckSubSaleClosedResult],
      ext: CheckSaleClosedResultExt) {

    self.saleOwner = saleOwner
    self.results = results
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.saleOwner.toXDR())
    xdr.append(self.results.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum CheckSaleClosedResultExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
