// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Result of the CheckSaleState operation along with the result code
//  union CheckSaleStateResult switch (CheckSaleStateResultCode code)
//  {
//  case SUCCESS:
//      CheckSaleStateSuccess success;
//  default:
//      void;
//  };

//  ===========================================================================
public enum CheckSaleStateResult: XDRDiscriminatedUnion {
  case success(CheckSaleStateSuccess)

  public var discriminant: Int32 {
    switch self {
    case .success: return CheckSaleStateResultCode.success.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    }

    return xdr
  }
}
