// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Result codes of CheckSaleState operation
//  enum CheckSaleStateResultCode
//  {
//      // codes considered as "success" for the operation
//      //: CheckSaleState operation was successfully applied
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      //: Sale with provided ID not found
//      NOT_FOUND = -1,
//      //: Sale was not processed, because it's still active
//      NOT_READY = -2
//  };

//  ===========================================================================
public enum CheckSaleStateResultCode: Int32, XDREnum {
  case success = 0
  case notFound = -1
  case notReady = -2
}
