// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct ClaimOfferAtom
//  {
//      // emitted to identify the offer
//      //: Address of the account that owns matched offer
//      AccountID bAccountID;
//      //: ID of the matched offer
//      uint64 offerID;
//      //: Amount in base asset taken during match
//      int64 baseAmount;
//      //: Amount in quote asset taked during match
//      int64 quoteAmount;
//      //: Fee paid by offer owner
//      int64 bFeePaid;
//      //: Fee paid by source of the operation
//      int64 aFeePaid;
//      //: Balance in base asset of offer owner
//      BalanceID baseBalance;
//      //: Balance in quote asset of offer owner
//      BalanceID quoteBalance;
//      //: Match price
//      int64 currentPrice;
//      //: Reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct ClaimOfferAtom: XDREncodable {
  public var bAccountID: AccountID
  public var offerID: Uint64
  public var baseAmount: Int64
  public var quoteAmount: Int64
  public var bFeePaid: Int64
  public var aFeePaid: Int64
  public var baseBalance: BalanceID
  public var quoteBalance: BalanceID
  public var currentPrice: Int64
  public var ext: ClaimOfferAtomExt

  public init(
      bAccountID: AccountID,
      offerID: Uint64,
      baseAmount: Int64,
      quoteAmount: Int64,
      bFeePaid: Int64,
      aFeePaid: Int64,
      baseBalance: BalanceID,
      quoteBalance: BalanceID,
      currentPrice: Int64,
      ext: ClaimOfferAtomExt) {

    self.bAccountID = bAccountID
    self.offerID = offerID
    self.baseAmount = baseAmount
    self.quoteAmount = quoteAmount
    self.bFeePaid = bFeePaid
    self.aFeePaid = aFeePaid
    self.baseBalance = baseBalance
    self.quoteBalance = quoteBalance
    self.currentPrice = currentPrice
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.bAccountID.toXDR())
    xdr.append(self.offerID.toXDR())
    xdr.append(self.baseAmount.toXDR())
    xdr.append(self.quoteAmount.toXDR())
    xdr.append(self.bFeePaid.toXDR())
    xdr.append(self.aFeePaid.toXDR())
    xdr.append(self.baseBalance.toXDR())
    xdr.append(self.quoteBalance.toXDR())
    xdr.append(self.currentPrice.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum ClaimOfferAtomExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
