// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum CloseSwapResultCode
//  {
//      //: CloseSwap was successful 
//      SUCCESS = 0,
//      //: Too late to close swap
//      SWAP_EXPIRED = -1,
//      //: Provided secret is invalid
//      INVALID_SECRET = -2,
//      //: After the swap fulfillment, the destination balance will exceed the limit (total amount on the balance will be greater than UINT64_MAX)
//      LINE_FULL = -3,
//      //: Source account is not authorized to close swap
//      NOT_AUTHORIZED = -4
//  };

//  ===========================================================================
public enum CloseSwapResultCode: Int32, XDREnum {
  case success = 0
  case swapExpired = -1
  case invalidSecret = -2
  case lineFull = -3
  case notAuthorized = -4
}
