// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum CreateSaleCreationRequestResultCode
//  {
//      // codes considered as "success" for the operation
//      //: CreateSaleCreationRequest operation was successfully applied
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      //: Trying to update reviewable request which does not exist
//      REQUEST_NOT_FOUND = -1,
//      //: Trying to create sale for asset which does not exist
//      BASE_ASSET_OR_ASSET_REQUEST_NOT_FOUND = -2,
//      //: Trying to create sale with quote asset which does not exist or
//      //: there is no asset pair with default quote asset and one of quote assets
//      QUOTE_ASSET_NOT_FOUND = -3,
//      //: Trying to create sale with start time > end time
//      START_END_INVALID = -4,
//      //: Trying to create sale with end time in the past
//      INVALID_END = -5,
//      //: Trying to create sale with 0 price
//      INVALID_PRICE = -6,
//      //: Trying to create sale with hard cap < soft cap
//      INVALID_CAP = -7,
//      //: Max issuance amount is less than sale's soft cap
//      INSUFFICIENT_MAX_ISSUANCE = -8,
//      //: Trying to create sale with invalid asset code of one of the assets or base asset is equal to one of the quote assets 
//      INVALID_ASSET_PAIR = -9,
//      //: Reviewable request or sale with the sale parameters already exists 
//      REQUEST_OR_SALE_ALREADY_EXISTS = -10,
//      //: Trying to create SaleCreationRequest with preissued amount lesser than hard cap
//      INSUFFICIENT_PREISSUED = -11,
//      //: Creator details must be a valid JSON 
//      INVALID_CREATOR_DETAILS = -12,
//      //: Version specified in the request is not supported yet
//      VERSION_IS_NOT_SUPPORTED_YET = -13,
//      //: Tasks for sale creation request were neither provided in the request nor loaded thru KeyValue
//      SALE_CREATE_TASKS_NOT_FOUND = -14,
//      //: Not allowed to set all tasks on rejected SaleCreationRequest update
//      NOT_ALLOWED_TO_SET_TASKS_ON_UPDATE = -15,
//      //: Due to tasks been 0, we have tried to auto review request, hovewer it failed
//      AUTO_REVIEW_FAILED = -16 
//  };

//  ===========================================================================
public enum CreateSaleCreationRequestResultCode: Int32, XDREnum {
  case success = 0
  case requestNotFound = -1
  case baseAssetOrAssetRequestNotFound = -2
  case quoteAssetNotFound = -3
  case startEndInvalid = -4
  case invalidEnd = -5
  case invalidPrice = -6
  case invalidCap = -7
  case insufficientMaxIssuance = -8
  case invalidAssetPair = -9
  case requestOrSaleAlreadyExists = -10
  case insufficientPreissued = -11
  case invalidCreatorDetails = -12
  case versionIsNotSupportedYet = -13
  case saleCreateTasksNotFound = -14
  case notAllowedToSetTasksOnUpdate = -15
  case autoReviewFailed = -16
}
