// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: CreateVoteData is used to pass needed params to create (send) vote
//  struct CreateVoteData
//  {
//      //: ID of poll to vote in
//      uint64 pollID;
//  
//      //: `data` is used to pass choice with functional type of poll
//      VoteData data;
//  
//      //: reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct CreateVoteData: XDRCodable {
  public var pollID: Uint64
  public var data: VoteData
  public var ext: CreateVoteDataExt

  public init(
      pollID: Uint64,
      data: VoteData,
      ext: CreateVoteDataExt) {

    self.pollID = pollID
    self.data = data
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.pollID.toXDR())
    xdr.append(self.data.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.pollID = try Uint64(xdrData: &xdrData)
    self.data = try VoteData(xdrData: &xdrData)
    self.ext = try CreateVoteDataExt(xdrData: &xdrData)
  }

  public enum CreateVoteDataExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion()
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
