// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: CreateSaleCreationRequest operation creates SaleCreationRequest or updates the rejected request
//  struct CreateSaleCreationRequestOp
//  {
//      //: ID of the SaleCreationRequest. If set to 0, a new request is created
//      uint64 requestID;
//      //: SaleCreationRequest details
//      SaleCreationRequest request;
//      //: (optional) Bit mask whose flags must be cleared in order for CreateSale request to be approved, which will be used by key sale_create_tasks:<asset_code>
//      //: instead of key-value
//      uint32* allTasks;
//      
//      //: Reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  
//  };

//  ===========================================================================
public struct CreateSaleCreationRequestOp: XDREncodable {
  public var requestID: Uint64
  public var request: SaleCreationRequest
  public var allTasks: Uint32?
  public var ext: CreateSaleCreationRequestOpExt

  public init(
      requestID: Uint64,
      request: SaleCreationRequest,
      allTasks: Uint32?,
      ext: CreateSaleCreationRequestOpExt) {

    self.requestID = requestID
    self.request = request
    self.allTasks = allTasks
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.requestID.toXDR())
    xdr.append(self.request.toXDR())
    xdr.append(self.allTasks.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum CreateSaleCreationRequestOpExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
