// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum CreateManageLimitsRequestResultCode
//  {
//      // codes considered as "success" for the operation
//      //: Operation was successfully applied and ManageLimitsRequest was successfully created
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      //: There is another manage limits request for source account
//      MANAGE_LIMITS_REQUEST_REFERENCE_DUPLICATION = -1,
//      //: There is no request with such ID
//      MANAGE_LIMITS_REQUEST_NOT_FOUND = -2,
//      //: Details must be valid json
//      INVALID_CREATOR_DETAILS = -3,
//      //: Cannot load tasks fot the CreateManageLimitsRequest or configuration restricts to create manage limits request
//      LIMITS_UPDATE_TASKS_NOT_FOUND = -5,
//      //: Cannot set allTasks on rejected request update
//      NOT_ALLOWED_TO_SET_TASKS_ON_UPDATE = -6,
//      //: 0 is not allowed value of `allTasks`, or not allowed for value entry, got by key limits_update_tasks:<asset_code>
//      LIMITS_UPDATE_ZERO_TASKS_NOT_ALLOWED = -7
//  };

//  ===========================================================================
public enum CreateManageLimitsRequestResultCode: Int32, XDREnum {
  case success = 0
  case manageLimitsRequestReferenceDuplication = -1
  case manageLimitsRequestNotFound = -2
  case invalidCreatorDetails = -3
  case limitsUpdateTasksNotFound = -5
  case notAllowedToSetTasksOnUpdate = -6
  case limitsUpdateZeroTasksNotAllowed = -7
}
