// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Result of operation applying
//  union CreateKYCRecoveryRequestResult switch (CreateKYCRecoveryRequestResultCode code)
//  {
//  case SUCCESS:
//      //: Is used to pass useful params if operation is success
//      struct {
//          //: id of the created request
//          uint64 requestID;
//  
//          //: Indicates whether or not the KYC Recovery request was auto approved and fulfilled
//          bool fulfilled;
//  
//          //: reserved for future use
//          union switch (LedgerVersion v)
//          {
//          case EMPTY_VERSION:
//              void;
//          }
//          ext;
//      } success;
//  default:
//      void;
//  };

//  ===========================================================================
public enum CreateKYCRecoveryRequestResult: XDRDiscriminatedUnion {
  case success(CreateKYCRecoveryRequestResultSuccess)

  public var discriminant: Int32 {
    switch self {
    case .success: return CreateKYCRecoveryRequestResultCode.success.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    }

    return xdr
  }

  public init(xdrData: inout Data) throws {
    let discriminant = try Int32(xdrData: &xdrData)

    switch discriminant {
    case CreateKYCRecoveryRequestResultCode.success.rawValue:
      let data = try CreateKYCRecoveryRequestResultSuccess(xdrData: &xdrData)
      self = .success(data)
    default:
      throw XDRErrors.unknownEnumCase
    }
  }
  public struct CreateKYCRecoveryRequestResultSuccess: XDRCodable {
    public var requestID: Uint64
    public var fulfilled: Bool
    public var ext: CreateKYCRecoveryRequestResultSuccessExt

    public init(
        requestID: Uint64,
        fulfilled: Bool,
        ext: CreateKYCRecoveryRequestResultSuccessExt) {

      self.requestID = requestID
      self.fulfilled = fulfilled
      self.ext = ext
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.requestID.toXDR())
      xdr.append(self.fulfilled.toXDR())
      xdr.append(self.ext.toXDR())

      return xdr
    }

    public init(xdrData: inout Data) throws {
      self.requestID = try Uint64(xdrData: &xdrData)
      self.fulfilled = try Bool(xdrData: &xdrData)
      self.ext = try CreateKYCRecoveryRequestResultSuccessExt(xdrData: &xdrData)
    }

    public enum CreateKYCRecoveryRequestResultSuccessExt: XDRDiscriminatedUnion {
      case emptyVersion

      public var discriminant: Int32 {
        switch self {
        case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
        }
      }

      public func toXDR() -> Data {
        var xdr = Data()

        xdr.append(self.discriminant.toXDR())

        switch self {
        case .emptyVersion: xdr.append(Data())
        }

        return xdr
      }

      public init(xdrData: inout Data) throws {
        let discriminant = try Int32(xdrData: &xdrData)

        switch discriminant {
        case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion
        default:
          throw XDRErrors.unknownEnumCase
        }
      }

    }
  }
}
