// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  union CreateSaleCreationRequestResult switch (CreateSaleCreationRequestResultCode code)
//  {
//  case SUCCESS:
//      CreateSaleCreationSuccess success;
//  case AUTO_REVIEW_FAILED:
//      CreateSaleCreationAutoReviewFailed autoReviewFailed;
//  default:
//      void;
//  };

//  ===========================================================================
public enum CreateSaleCreationRequestResult: XDRDiscriminatedUnion {
  case success(CreateSaleCreationSuccess)
  case autoReviewFailed(CreateSaleCreationAutoReviewFailed)

  public var discriminant: Int32 {
    switch self {
    case .success: return CreateSaleCreationRequestResultCode.success.rawValue
    case .autoReviewFailed: return CreateSaleCreationRequestResultCode.autoReviewFailed.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    case .autoReviewFailed(let data): xdr.append(data.toXDR())
    }

    return xdr
  }
}
