// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  union CreateASwapBidCreationRequestResult switch (CreateASwapBidCreationRequestResultCode code)
//  {
//  case SUCCESS:
//      CreateASwapBidCreationRequestSuccess success;
//  default:
//      void;
//  };

//  ===========================================================================
public enum CreateASwapBidCreationRequestResult: XDRDiscriminatedUnion {
  case success(CreateASwapBidCreationRequestSuccess)

  public var discriminant: Int32 {
    switch self {
    case .success: return CreateASwapBidCreationRequestResultCode.success.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    }

    return xdr
  }
}
