// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: `CreateManageLimitsRequestResult` represents the result of the `CreateManageLimitsRequestOp` with corresponding details based on given `CreateManageLimitsRequestResultCode`
//  union CreateManageLimitsRequestResult switch (CreateManageLimitsRequestResultCode code)
//  {
//  case SUCCESS:
//      struct {
//          //: ID of the created manage limits request
//          uint64 manageLimitsRequestID;
//          //: Indicates whether or not the `limits update request` request was auto approved and fulfilled
//          bool fulfilled;
//          //: reserved for future use
//          union switch (LedgerVersion v)
//          {
//          case EMPTY_VERSION:
//              void;
//          }
//          ext;
//      } success;
//  default:
//      void;
//  };

//  ===========================================================================
public enum CreateManageLimitsRequestResult: XDRDiscriminatedUnion {
  case success(CreateManageLimitsRequestResultSuccess)

  public var discriminant: Int32 {
    switch self {
    case .success: return CreateManageLimitsRequestResultCode.success.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    }

    return xdr
  }

  public init(xdrData: inout Data) throws {
    let discriminant = try Int32(xdrData: &xdrData)

    switch discriminant {
    case CreateManageLimitsRequestResultCode.success.rawValue:
      let data = try CreateManageLimitsRequestResultSuccess(xdrData: &xdrData)
      self = .success(data)
    default:
      throw XDRErrors.unknownEnumCase
    }
  }
  public struct CreateManageLimitsRequestResultSuccess: XDRCodable {
    public var manageLimitsRequestID: Uint64
    public var fulfilled: Bool
    public var ext: CreateManageLimitsRequestResultSuccessExt

    public init(
        manageLimitsRequestID: Uint64,
        fulfilled: Bool,
        ext: CreateManageLimitsRequestResultSuccessExt) {

      self.manageLimitsRequestID = manageLimitsRequestID
      self.fulfilled = fulfilled
      self.ext = ext
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.manageLimitsRequestID.toXDR())
      xdr.append(self.fulfilled.toXDR())
      xdr.append(self.ext.toXDR())

      return xdr
    }

    public init(xdrData: inout Data) throws {
      self.manageLimitsRequestID = try Uint64(xdrData: &xdrData)
      self.fulfilled = try Bool(xdrData: &xdrData)
      self.ext = try CreateManageLimitsRequestResultSuccessExt(xdrData: &xdrData)
    }

    public enum CreateManageLimitsRequestResultSuccessExt: XDRDiscriminatedUnion {
      case emptyVersion()

      public var discriminant: Int32 {
        switch self {
        case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
        }
      }

      public func toXDR() -> Data {
        var xdr = Data()

        xdr.append(self.discriminant.toXDR())

        switch self {
        case .emptyVersion(): xdr.append(Data())
        }

        return xdr
      }

      public init(xdrData: inout Data) throws {
        let discriminant = try Int32(xdrData: &xdrData)

        switch discriminant {
        case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion()
        default:
          throw XDRErrors.unknownEnumCase
        }
      }

    }
  }
}
