// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: CreateCloseDeferredPaymentRequestOp is used to create `CLOSE_DEFERRED_PAYMENT` request
//  struct CreateCloseDeferredPaymentRequestOp
//  {
//  
//      uint64 requestID;
//  
//      //: Body of request which will be created
//      CloseDeferredPaymentRequest request;
//  
//      uint32* allTasks;
//      //: reserved for the future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct CreateCloseDeferredPaymentRequestOp: XDRCodable {
  public var requestID: Uint64
  public var request: CloseDeferredPaymentRequest
  public var allTasks: Uint32?
  public var ext: CreateCloseDeferredPaymentRequestOpExt

  public init(
      requestID: Uint64,
      request: CloseDeferredPaymentRequest,
      allTasks: Uint32?,
      ext: CreateCloseDeferredPaymentRequestOpExt) {

    self.requestID = requestID
    self.request = request
    self.allTasks = allTasks
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.requestID.toXDR())
    xdr.append(self.request.toXDR())
    xdr.append(self.allTasks.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.requestID = try Uint64(xdrData: &xdrData)
    self.request = try CloseDeferredPaymentRequest(xdrData: &xdrData)
    if (try Bool(xdrData: &xdrData)) {
      self.allTasks = try Uint32(xdrData: &xdrData)
    } else {
      self.allTasks = nil
    }
    self.ext = try CreateCloseDeferredPaymentRequestOpExt(xdrData: &xdrData)
  }

  public enum CreateCloseDeferredPaymentRequestOpExt: XDRDiscriminatedUnion {
    case emptyVersion

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion: xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
