// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum CreateIssuanceRequestResultCode
//  {
//      // codes considered as "success" for the operation
//      //: CreateIssuanceRequest operation application was successful
//      SUCCESS = 0,
//      
//      // codes considered as "failure" for the operation
//      //: Asset to issue not found
//      ASSET_NOT_FOUND = -1,
//      //: Trying to create issuance request with negative/zero amount
//      INVALID_AMOUNT = -2,
//      //: Request with the same reference already exists
//      REFERENCE_DUPLICATION = -3,
//      //: Target balance not found or asset of the target balance and asset in the request mismatched
//      NO_COUNTERPARTY = -4,
//      //: Source of the operation is not an owner of the asset 
//      NOT_AUTHORIZED = -5,
//      //: Issued amount plus amount to issue will exceed max issuance amount
//      EXCEEDS_MAX_ISSUANCE_AMOUNT = -6,
//      //: Amount to issue plus amount on balance would exceed UINT64_MAX 
//      RECEIVER_FULL_LINE = -7,
//      //: Creator details are not valid JSON
//      INVALID_CREATOR_DETAILS = -8,
//      //: Fee is greater than amount to issue
//      FEE_EXCEEDS_AMOUNT = -9,
//      //: Deprecated
//      REQUIRES_KYC = -10,
//      //: Deprecated
//      REQUIRES_VERIFICATION = -11, //asset requires receiver to be verified
//      //: Issuance tasks are not set in the system, i.e. it's not allowed to perform issuance
//      ISSUANCE_TASKS_NOT_FOUND = -12,
//      //: Not allowed to set system tasks: 1, 2, 4
//      SYSTEM_TASKS_NOT_ALLOWED = -13,
//      //: Amount precision and asset precision are mismatched
//      INVALID_AMOUNT_PRECISION = -14
//  };

//  ===========================================================================
public enum CreateIssuanceRequestResultCode: Int32, XDREnum {
  case success = 0
  case assetNotFound = -1
  case invalidAmount = -2
  case referenceDuplication = -3
  case noCounterparty = -4
  case notAuthorized = -5
  case exceedsMaxIssuanceAmount = -6
  case receiverFullLine = -7
  case invalidCreatorDetails = -8
  case feeExceedsAmount = -9
  case requiresKyc = -10
  case requiresVerification = -11
  case issuanceTasksNotFound = -12
  case systemTasksNotAllowed = -13
  case invalidAmountPrecision = -14
}
