// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum CreateManageOfferRequestResultCode 
//  {
//      //: CreateManageOfferRequestOp was successfully applied
//      SUCCESS = 0,
//  
//      //: Offer is invalid
//      INVALID_OFFER = -1,
//      //: Tasks for the manage offer request were neither provided in the request nor loaded through KeyValue
//      MANAGE_OFFER_TASKS_NOT_FOUND = -2,
//      //: Creator details are not in a valid JSON format
//      INVALID_CREATOR_DETAILS = -3
//  };

//  ===========================================================================
public enum CreateManageOfferRequestResultCode: Int32, XDREnum {
  case success = 0
  case invalidOffer = -1
  case manageOfferTasksNotFound = -2
  case invalidCreatorDetails = -3
}
