// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Result codes of CreateAtomicSwapBidRequestOp
//  enum CreateCloseDeferredPaymentRequestResultCode
//  {
//      //: `CLOSE_DEFERRED_PAYMENT` request has either been successfully created
//      //: or auto approved
//      SUCCESS = 0,
//  
//      UNDERFUNDED = -1,
//      INVALID_CREATOR_DETAILS = -2,
//      NOT_AUTHORIZED = -3,
//      DESTINATION_ACCOUNT_NOT_FOUND = -4,
//      INCORRECT_PRECISION = -5,
//      ASSET_MISMATCH = -6,
//      LINE_FULL = -7,
//      TASKS_NOT_FOUND = -8,
//      INVALID_AMOUNT = -9,
//      DESTINATION_BALANCE_NOT_FOUND = -10,
//      REQUEST_NOT_FOUND = -11
//  };

//  ===========================================================================
public enum CreateCloseDeferredPaymentRequestResultCode: Int32, XDREnum {
  case success = 0
  case underfunded = -1
  case invalidCreatorDetails = -2
  case notAuthorized = -3
  case destinationAccountNotFound = -4
  case incorrectPrecision = -5
  case assetMismatch = -6
  case lineFull = -7
  case tasksNotFound = -8
  case invalidAmount = -9
  case destinationBalanceNotFound = -10
  case requestNotFound = -11
}
