// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Success request of CreateAtomicSwapBidRequestOp application
//  struct CreateAtomicSwapBidRequestSuccess
//  {
//      //: id of created request
//      uint64 requestID;
//      //: id of ask owner
//      AccountID askOwnerID;
//      //: amount in quote asset which required for request applying
//      uint64 quoteAmount;
//  
//      //: reserved for the future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct CreateAtomicSwapBidRequestSuccess: XDRCodable {
  public var requestID: Uint64
  public var askOwnerID: AccountID
  public var quoteAmount: Uint64
  public var ext: CreateAtomicSwapBidRequestSuccessExt

  public init(
      requestID: Uint64,
      askOwnerID: AccountID,
      quoteAmount: Uint64,
      ext: CreateAtomicSwapBidRequestSuccessExt) {

    self.requestID = requestID
    self.askOwnerID = askOwnerID
    self.quoteAmount = quoteAmount
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.requestID.toXDR())
    xdr.append(self.askOwnerID.toXDR())
    xdr.append(self.quoteAmount.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.requestID = try Uint64(xdrData: &xdrData)
    self.askOwnerID = try AccountID(xdrData: &xdrData)
    self.quoteAmount = try Uint64(xdrData: &xdrData)
    self.ext = try CreateAtomicSwapBidRequestSuccessExt(xdrData: &xdrData)
  }

  public enum CreateAtomicSwapBidRequestSuccessExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion()
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
