// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Result of the successful withdrawal request creation
//  struct CreateWithdrawalSuccess {
//      //: ID of a newly created WithdrawalRequest
//      uint64 requestID;
//      //: Indicates whether or not the withdrawal request was auto approved and fulfilled
//      bool fulfilled;
//      //: Reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct CreateWithdrawalSuccess: XDREncodable {
  public var requestID: Uint64
  public var fulfilled: Bool
  public var ext: CreateWithdrawalSuccessExt

  public init(
      requestID: Uint64,
      fulfilled: Bool,
      ext: CreateWithdrawalSuccessExt) {

    self.requestID = requestID
    self.fulfilled = fulfilled
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.requestID.toXDR())
    xdr.append(self.fulfilled.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum CreateWithdrawalSuccessExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
