// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct CreateAMLAlertRequestOp
//  {
//      //: Reference of AMLAlertRequest
//      string64 reference; // TODO longstring ?
//      //: Parameters of AMLAlertRequest
//      AMLAlertRequest amlAlertRequest;
//      //: (optional) Bit mask whose flags must be cleared in order for AMLAlertRequest to be approved, which will be used
//      //: instead of key-value by key aml_alert_tasks:<asset_code>
//      uint32* allTasks;
//  
//      //: Reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  
//  };

//  ===========================================================================
public struct CreateAMLAlertRequestOp: XDREncodable {
  public var reference: String64
  public var amlAlertRequest: AMLAlertRequest
  public var allTasks: Uint32?
  public var ext: CreateAMLAlertRequestOpExt

  public init(
      reference: String64,
      amlAlertRequest: AMLAlertRequest,
      allTasks: Uint32?,
      ext: CreateAMLAlertRequestOpExt) {

    self.reference = reference
    self.amlAlertRequest = amlAlertRequest
    self.allTasks = allTasks
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.reference.toXDR())
    xdr.append(self.amlAlertRequest.toXDR())
    xdr.append(self.allTasks.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum CreateAMLAlertRequestOpExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
