// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: CreateSignerRuleData is used to pass necessary params to create a new signer rule
//  struct CreateSignerRuleData
//  {
//      //: Resource is used to specify an entity (for some, with properties) that can be managed through operations
//      SignerRuleResource resource;
//      //: Value from enum that can be applied to `resource`
//      SignerRuleAction action;
//      //: Indicate whether or not an `action` on the provided `resource` is prohibited
//      bool forbids;
//      //: True means that such rule will be automatically added to each new or updated signer role
//      bool isDefault;
//      //: Indicates whether or not a rule can be modified in the future
//      bool isReadOnly;
//      //: Arbitrary stringified json object with details that will be attached to a rule
//      longstring details;
//  
//      // reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct CreateSignerRuleData: XDRCodable {
  public var resource: SignerRuleResource
  public var action: SignerRuleAction
  public var forbids: Bool
  public var isDefault: Bool
  public var isReadOnly: Bool
  public var details: Longstring
  public var ext: CreateSignerRuleDataExt

  public init(
      resource: SignerRuleResource,
      action: SignerRuleAction,
      forbids: Bool,
      isDefault: Bool,
      isReadOnly: Bool,
      details: Longstring,
      ext: CreateSignerRuleDataExt) {

    self.resource = resource
    self.action = action
    self.forbids = forbids
    self.isDefault = isDefault
    self.isReadOnly = isReadOnly
    self.details = details
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.resource.toXDR())
    xdr.append(self.action.toXDR())
    xdr.append(self.forbids.toXDR())
    xdr.append(self.isDefault.toXDR())
    xdr.append(self.isReadOnly.toXDR())
    xdr.append(self.details.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.resource = try SignerRuleResource(xdrData: &xdrData)
    self.action = try SignerRuleAction(xdrData: &xdrData)
    self.forbids = try Bool(xdrData: &xdrData)
    self.isDefault = try Bool(xdrData: &xdrData)
    self.isReadOnly = try Bool(xdrData: &xdrData)
    self.details = try Longstring(xdrData: &xdrData)
    self.ext = try CreateSignerRuleDataExt(xdrData: &xdrData)
  }

  public enum CreateSignerRuleDataExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion()
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
