// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum CreateASwapBidCreationRequestResultCode
//  {
//      // codes considered as "success" for the operation
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      INVALID_AMOUNT = -1, // amount is equal to 0
//      INVALID_PRICE = -2, // price is equal to 0
//      INVALID_DETAILS = -3,
//      ATOMIC_SWAP_BID_OVERFLOW = -4,
//      BASE_ASSET_NOT_FOUND = -5, // base asset does not exist
//      BASE_ASSET_CANNOT_BE_SWAPPED = -6,
//      QUOTE_ASSET_NOT_FOUND = -7, // quote asset does not exist
//      QUOTE_ASSET_CANNOT_BE_SWAPPED = -8,
//      BASE_BALANCE_NOT_FOUND = -9,
//      ASSETS_ARE_EQUAL = -10, // base and quote assets are the same
//      BASE_BALANCE_UNDERFUNDED = -11,
//      INVALID_QUOTE_ASSET = -12, // one of the quote assets is invalid
//      NOT_ALLOWED_BY_ASSET_POLICY = -13
//  };

//  ===========================================================================
public enum CreateASwapBidCreationRequestResultCode: Int32, XDREnum {
  case success = 0
  case invalidAmount = -1
  case invalidPrice = -2
  case invalidDetails = -3
  case atomicSwapBidOverflow = -4
  case baseAssetNotFound = -5
  case baseAssetCannotBeSwapped = -6
  case quoteAssetNotFound = -7
  case quoteAssetCannotBeSwapped = -8
  case baseBalanceNotFound = -9
  case assetsAreEqual = -10
  case baseBalanceUnderfunded = -11
  case invalidQuoteAsset = -12
  case notAllowedByAssetPolicy = -13
}
