// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Success result of CreateASwapAskCreationRequestOp application
//  struct CreateAtomicSwapAskRequestSuccess
//  {
//      //: id of created request
//      uint64 requestID;
//      //: Indicates whether or not the `CREATE_ATOMIC_SWAP_ASK` request was auto approved and fulfilled
//      bool fulfilled;
//      //: ID of a newly created ask (if the ask  creation request has been auto approved)
//      uint64 askID;
//  
//      //: reserved for the future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct CreateAtomicSwapAskRequestSuccess: XDREncodable {
  public var requestID: Uint64
  public var fulfilled: Bool
  public var askID: Uint64
  public var ext: CreateAtomicSwapAskRequestSuccessExt

  public init(
      requestID: Uint64,
      fulfilled: Bool,
      askID: Uint64,
      ext: CreateAtomicSwapAskRequestSuccessExt) {

    self.requestID = requestID
    self.fulfilled = fulfilled
    self.askID = askID
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.requestID.toXDR())
    xdr.append(self.fulfilled.toXDR())
    xdr.append(self.askID.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum CreateAtomicSwapAskRequestSuccessExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
