// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct CreateASwapRequestSuccess
//  {
//      uint64 requestID;
//      AccountID bidOwnerID;
//  
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct CreateASwapRequestSuccess: XDREncodable {
  public var requestID: Uint64
  public var bidOwnerID: AccountID
  public var ext: CreateASwapRequestSuccessExt

  public init(
      requestID: Uint64,
      bidOwnerID: AccountID,
      ext: CreateASwapRequestSuccessExt) {

    self.requestID = requestID
    self.bidOwnerID = bidOwnerID
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.requestID.toXDR())
    xdr.append(self.bidOwnerID.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum CreateASwapRequestSuccessExt: XDRDiscriminatedUnion {
    case emptyVersion

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion: xdr.append(Data())
      }

      return xdr
    }

  }
}
