// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Describes custom rule resource that can be used outside of the Core for flexible access control
//  struct CustomRuleResource {
//      //: Action attributes
//      longstring *action;
//      //: Resource attributes
//      longstring resource;
//  
//      EmptyExt ext;
//  };

//  ===========================================================================
public struct CustomRuleResource: XDRCodable {
  public var action: Longstring?
  public var resource: Longstring
  public var ext: EmptyExt

  public init(
      action: Longstring?,
      resource: Longstring,
      ext: EmptyExt) {

    self.action = action
    self.resource = resource
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.action.toXDR())
    xdr.append(self.resource.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    if (try Bool(xdrData: &xdrData)) {
      self.action = try Longstring(xdrData: &xdrData)
    } else {
      self.action = nil
    }
    self.resource = try Longstring(xdrData: &xdrData)
    self.ext = try EmptyExt(xdrData: &xdrData)
  }
}
