// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct DeferredPaymentEntry
//  {
//      //: ID of the deferred payment entry
//      uint64 id;
//  
//      uint64 amount;
//  
//      longstring details;
//  
//      //: Creator of the entry
//      AccountID source;
//      BalanceID sourceBalance;
//  
//      AccountID destination;
//  
//      //: Reserved for future extension
//      EmptyExt ext;
//  };

//  ===========================================================================
public struct DeferredPaymentEntry: XDRCodable {
  public var id: Uint64
  public var amount: Uint64
  public var details: Longstring
  public var source: AccountID
  public var sourceBalance: BalanceID
  public var destination: AccountID
  public var ext: EmptyExt

  public init(
      id: Uint64,
      amount: Uint64,
      details: Longstring,
      source: AccountID,
      sourceBalance: BalanceID,
      destination: AccountID,
      ext: EmptyExt) {

    self.id = id
    self.amount = amount
    self.details = details
    self.source = source
    self.sourceBalance = sourceBalance
    self.destination = destination
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.id.toXDR())
    xdr.append(self.amount.toXDR())
    xdr.append(self.details.toXDR())
    xdr.append(self.source.toXDR())
    xdr.append(self.sourceBalance.toXDR())
    xdr.append(self.destination.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.id = try Uint64(xdrData: &xdrData)
    self.amount = try Uint64(xdrData: &xdrData)
    self.details = try Longstring(xdrData: &xdrData)
    self.source = try AccountID(xdrData: &xdrData)
    self.sourceBalance = try BalanceID(xdrData: &xdrData)
    self.destination = try AccountID(xdrData: &xdrData)
    self.ext = try EmptyExt(xdrData: &xdrData)
  }
}
