// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct DontHave
//  {
//      MessageType type;
//      uint256 reqHash;
//  };

//  ===========================================================================
public struct DontHave: XDREncodable {
  public var type: MessageType
  public var reqHash: Uint256

  public init(
      type: MessageType,
      reqHash: Uint256) {

    self.type = type
    self.reqHash = reqHash
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.type.toXDR())
    xdr.append(self.reqHash.toXDR())

    return xdr
  }
}
