// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum EmissionFeeType
//  {
//      PRIMARY_MARKET = 1,
//      SECONDARY_MARKET = 2
//  };

//  ===========================================================================
public enum EmissionFeeType: Int32, XDREnum {
  case primaryMarket = 1
  case secondaryMarket = 2
}
