// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  union EmptyExt switch (LedgerVersion v)
//  {
//  case EMPTY_VERSION:
//      void;
//  };

//  ===========================================================================
public enum EmptyExt: XDRDiscriminatedUnion {
  case emptyVersion()

  public var discriminant: Int32 {
    switch self {
    case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .emptyVersion(): xdr.append(Data())
    }

    return xdr
  }
}
