// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum EnvelopeType
//  {
//      SCP = 1,
//      TX = 2,
//      AUTH = 3
//  };

//  ===========================================================================
public enum EnvelopeType: Int32, XDREnum {
  case scp = 1
  case tx = 2
  case auth = 3
}
