// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct Error
//  {
//      ErrorCode code;
//      string msg<100>;
//  };

//  ===========================================================================
public struct Error: XDREncodable {
  public var code: ErrorCode
  public var msg: String

  public init(
      code: ErrorCode,
      msg: String) {

    self.code = code
    self.msg = msg
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.code.toXDR())
    xdr.append(self.msg.toXDR())

    return xdr
  }
}
