// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct HmacSha256Mac
//  {
//          opaque mac[32];
//  };

//  ===========================================================================
public struct HmacSha256Mac: XDRCodable {
  public var mac: XDRDataFixed32

  public init(
      mac: XDRDataFixed32) {

    self.mac = mac
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.mac.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.mac = try XDRDataFixed32(xdrData: &xdrData)
  }
}
