// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct ImmediateSale {
//      EmptyExt ext;
//  };

//  ===========================================================================
public struct ImmediateSale: XDRCodable {
  public var ext: EmptyExt

  public init(
      ext: EmptyExt) {

    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.ext = try EmptyExt(xdrData: &xdrData)
  }
}
