// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  union LedgerUpgrade switch (LedgerUpgradeType type)
//  {
//  case VERSION:
//      uint32 newLedgerVersion; // update ledgerVersion
//  case MAX_TX_SET_SIZE:
//      uint32 newMaxTxSetSize; // update maxTxSetSize
//  case TX_EXPIRATION_PERIOD:
//      int64 newTxExpirationPeriod;
//  };

//  ===========================================================================
public enum LedgerUpgrade: XDRDiscriminatedUnion {
  case version(Uint32)
  case maxTxSetSize(Uint32)
  case txExpirationPeriod(Int64)

  public var discriminant: Int32 {
    switch self {
    case .version: return LedgerUpgradeType.version.rawValue
    case .maxTxSetSize: return LedgerUpgradeType.maxTxSetSize.rawValue
    case .txExpirationPeriod: return LedgerUpgradeType.txExpirationPeriod.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .version(let data): xdr.append(data.toXDR())
    case .maxTxSetSize(let data): xdr.append(data.toXDR())
    case .txExpirationPeriod(let data): xdr.append(data.toXDR())
    }

    return xdr
  }
}
