// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum LPSwapResultCode
//      {
//          //: LP swap was successful
//          SUCCESS = 0,
//  
//          //: Source and target balances are the same
//          SAME_BALANCES = -1,
//          //: Not enough funds in the source account
//          UNDERFUNDED = -2,
//          //: Sender balance asset and receiver balance asset are not equal
//          BALANCE_ASSETS_MATCHED = -3,
//          //: There is no balance found with ID provided in `fromBalance`
//          FROM_BALANCE_NOT_FOUND = -4,
//          //: There is no balance found with ID provided in `toBalance`
//          TO_BALANCE_NOT_FOUND = -5,
//          //: Payment asset does not have a `SWAPPABLE` policy set
//          NOT_ALLOWED_BY_ASSET_POLICY = -6,
//          //: Overflow during total fee calculation
//          INVALID_DESTINATION_FEE = -7,
//          //: Payment fee amount is insufficient
//          INSUFFICIENT_FEE_AMOUNT = -8,
//          //: Fee charged from destination balance is greater than the amount
//          AMOUNT_IS_LESS_THAN_DEST_FEE = -9,
//          //: Amount precision and asset precision are mismatched
//          INCORRECT_AMOUNT_PRECISION = -10,
//          //: Zero input amount not allowed
//          INSUFFICIENT_INPUT_AMOUNT = -11,
//          //: Output amount is less than allowed 
//          INSUFFICIENT_OUTPUT_AMOUNT = -12,
//          //: From and to assets are the same
//          SAME_ASSETS = -13,
//          //: Liquidity pool for assets from balances not found
//          LIQUIDITY_POOL_NOT_FOUND = -14,
//          //: Reserves of the liquidity pool are insufficient for swap
//          INSUFFICIENT_LIQUIDITY = -15,
//          //: Calculated input amount is greater than provided amountInMax
//          EXCESSIVE_INPUT_AMOUNT = -16,
//          //: The destination balance will exceed the limit (total amount on the balance will be greater than UINT64_MAX) 
//          BALANCE_OVERFLOW = -17
//      };

//  ===========================================================================
public enum LPSwapResultCode: Int32, XDREnum {
  case success = 0
  case sameBalances = -1
  case underfunded = -2
  case balanceAssetsMatched = -3
  case fromBalanceNotFound = -4
  case toBalanceNotFound = -5
  case notAllowedByAssetPolicy = -6
  case invalidDestinationFee = -7
  case insufficientFeeAmount = -8
  case amountIsLessThanDestFee = -9
  case incorrectAmountPrecision = -10
  case insufficientInputAmount = -11
  case insufficientOutputAmount = -12
  case sameAssets = -13
  case liquidityPoolNotFound = -14
  case insufficientLiquidity = -15
  case excessiveInputAmount = -16
  case balanceOverflow = -17
}
