// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum ManageBalanceAction
//  {
//      //: Create new balance
//      CREATE = 0,
//      //: Delete existing balance by ID
//      DELETE_BALANCE = 1,
//      //: Ensure that the balance will not be created if the balance of the provided Asset exists and is attached to provided Account
//      CREATE_UNIQUE = 2
//  };

//  ===========================================================================
public enum ManageBalanceAction: Int32, XDREnum {
  case create = 0
  case deleteBalance = 1
  case createUnique = 2
}
