// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum ManageContractRequestResultCode
//  {
//      // codes considered as "success" for the operation
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      MALFORMED = -1,
//      NOT_FOUND = -2, // not found contract request, when try to remove
//      TOO_MANY_CONTRACTS = -3,
//      NOT_ALLOWED_TO_REMOVE = -4, // only contract creator can remove contract
//      DETAILS_TOO_LONG = -5,
//      CONTRACT_CREATE_TASKS_NOT_FOUND = -6 // key-value not set
//  };

//  ===========================================================================
public enum ManageContractRequestResultCode: Int32, XDREnum {
  case success = 0
  case malformed = -1
  case notFound = -2
  case tooManyContracts = -3
  case notAllowedToRemove = -4
  case detailsTooLong = -5
  case contractCreateTasksNotFound = -6
}
