// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum ManageKVAction
//      {
//          PUT = 1,
//          REMOVE = 2
//      };

//  ===========================================================================
public enum ManageKVAction: Int32, XDREnum {
  case put = 1
  case remove = 2
}
