// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //:Result of ManageSale operation successful application 
//  struct ManageSaleResultSuccess
//  {
//      //: Indicates  whether or not the ManageSale request was auto approved and fulfilled
//      bool fulfilled; // can be used for any reviewable request type created with manage sale operation   
//  
//      //: response is used for additional information regarding the action performed on sale during operation application
//      union switch (ManageSaleAction action) {
//      case CREATE_UPDATE_DETAILS_REQUEST:
//          uint64 requestID;
//      case CANCEL:
//          void;
//      } response;
//  
//      //: Reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct ManageSaleResultSuccess: XDREncodable {
  public var fulfilled: Bool
  public var response: ManageSaleResultSuccessResponse
  public var ext: ManageSaleResultSuccessExt

  public init(
      fulfilled: Bool,
      response: ManageSaleResultSuccessResponse,
      ext: ManageSaleResultSuccessExt) {

    self.fulfilled = fulfilled
    self.response = response
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.fulfilled.toXDR())
    xdr.append(self.response.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum ManageSaleResultSuccessResponse: XDRDiscriminatedUnion {
    case createUpdateDetailsRequest(Uint64)
    case cancel()

    public var discriminant: Int32 {
      switch self {
      case .createUpdateDetailsRequest: return ManageSaleAction.createUpdateDetailsRequest.rawValue
      case .cancel: return ManageSaleAction.cancel.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .createUpdateDetailsRequest(let data): xdr.append(data.toXDR())
      case .cancel(): xdr.append(Data())
      }

      return xdr
    }

  }
  public enum ManageSaleResultSuccessExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
