// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Actions that can be performed on the asset pair
//  enum ManageAssetPairAction
//  {
//      //: Create new asset pair
//      CREATE = 0,
//      //: Update price of the asset pair
//      UPDATE_PRICE = 1,
//      //: Update asset pair policies bitmask
//      UPDATE_POLICIES = 2
//  };

//  ===========================================================================
public enum ManageAssetPairAction: Int32, XDREnum {
  case create = 0
  case updatePrice = 1
  case updatePolicies = 2
}
