// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Actions that can be performed with account specific rule
//  enum ManageAccountSpecificRuleAction
//  {
//      CREATE = 0,
//      REMOVE = 1
//  };

//  ===========================================================================
public enum ManageAccountSpecificRuleAction: Int32, XDREnum {
  case create = 0
  case remove = 1
}
