// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct ManageOfferRequest 
//  {
//      ManageOfferOp op;
//  
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      case MOVEMENT_REQUESTS_DETAILS:
//          longstring creatorDetails;
//      } ext;
//  };

//  ===========================================================================
public struct ManageOfferRequest: XDRCodable {
  public var op: ManageOfferOp
  public var ext: ManageOfferRequestExt

  public init(
      op: ManageOfferOp,
      ext: ManageOfferRequestExt) {

    self.op = op
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.op.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.op = try ManageOfferOp(xdrData: &xdrData)
    self.ext = try ManageOfferRequestExt(xdrData: &xdrData)
  }

  public enum ManageOfferRequestExt: XDRDiscriminatedUnion {
    case emptyVersion()
    case movementRequestsDetails(Longstring)

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      case .movementRequestsDetails: return LedgerVersion.movementRequestsDetails.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      case .movementRequestsDetails(let data): xdr.append(data.toXDR())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion()
      case LedgerVersion.movementRequestsDetails.rawValue:
        let data = try Longstring(xdrData: &xdrData)
        self = .movementRequestsDetails(data)
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
