// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Actions that can be performed with account rule
//  enum ManageAccountRuleAction
//  {
//      CREATE = 0,
//      UPDATE = 1,
//      REMOVE = 2
//  };

//  ===========================================================================
public enum ManageAccountRuleAction: Int32, XDREnum {
  case create = 0
  case update = 1
  case remove = 2
}
