// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum ManageContractResultCode
//  {
//      // codes considered as "success" for the operation
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      MALFORMED = -1,
//      NOT_FOUND = -2, // not found contract
//      NOT_ALLOWED = -3, // only contractor or customer can add details
//      DETAILS_TOO_LONG = -4,
//      DISPUTE_REASON_TOO_LONG = -5,
//      ALREADY_CONFIRMED = -6,
//      INVOICE_NOT_APPROVED = -7, // all contract invoices must be approved
//      DISPUTE_ALREADY_STARTED = -8,
//      CUSTOMER_BALANCE_OVERFLOW = -9,
//      INCORRECT_PRECISION = -10
//  };

//  ===========================================================================
public enum ManageContractResultCode: Int32, XDREnum {
  case success = 0
  case malformed = -1
  case notFound = -2
  case notAllowed = -3
  case detailsTooLong = -4
  case disputeReasonTooLong = -5
  case alreadyConfirmed = -6
  case invoiceNotApproved = -7
  case disputeAlreadyStarted = -8
  case customerBalanceOverflow = -9
  case incorrectPrecision = -10
}
