// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  union ManageSaleResult switch (ManageSaleResultCode code)
//  {
//  case SUCCESS:
//      ManageSaleResultSuccess success;
//  default:
//      void;
//  };

//  ===========================================================================
public enum ManageSaleResult: XDRDiscriminatedUnion {
  case success(ManageSaleResultSuccess)

  public var discriminant: Int32 {
    switch self {
    case .success: return ManageSaleResultCode.success.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    }

    return xdr
  }
}
