// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum ManageInvoiceRequestResultCode
//  {
//      // codes considered as "success" for the operation
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      MALFORMED = -1,
//      BALANCE_NOT_FOUND = -2, // sender balance not found
//      NOT_FOUND = -3, // not found invoice request, when try to remove
//      TOO_MANY_INVOICES = -4,
//      DETAILS_TOO_LONG = -5,
//      NOT_ALLOWED_TO_REMOVE = -6, // only invoice creator can remove invoice
//      CONTRACT_NOT_FOUND = -7,
//      ONLY_CONTRACTOR_CAN_ATTACH_INVOICE_TO_CONTRACT = -8,
//      SENDER_ACCOUNT_MISMATCHED = -9,
//      INVOICE_IS_APPROVED = -10, // not allowed to remove approved invoice
//      INVOICE_TASKS_NOT_FOUND = -11
//  };

//  ===========================================================================
public enum ManageInvoiceRequestResultCode: Int32, XDREnum {
  case success = 0
  case malformed = -1
  case balanceNotFound = -2
  case notFound = -3
  case tooManyInvoices = -4
  case detailsTooLong = -5
  case notAllowedToRemove = -6
  case contractNotFound = -7
  case onlyContractorCanAttachInvoiceToContract = -8
  case senderAccountMismatched = -9
  case invoiceIsApproved = -10
  case invoiceTasksNotFound = -11
}
