// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Is used to return the result of operation application
//  union ManageAssetResult switch (ManageAssetResultCode code)
//  {
//  case SUCCESS:
//      //: Result of successful operation application
//      ManageAssetSuccess success;
//  default:
//      void;
//  };

//  ===========================================================================
public enum ManageAssetResult: XDRDiscriminatedUnion {
  case success(ManageAssetSuccess)

  public var discriminant: Int32 {
    switch self {
    case .success: return ManageAssetResultCode.success.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    }

    return xdr
  }

  public init(xdrData: inout Data) throws {
    let discriminant = try Int32(xdrData: &xdrData)

    switch discriminant {
    case ManageAssetResultCode.success.rawValue:
      let data = try ManageAssetSuccess(xdrData: &xdrData)
      self = .success(data)
    default:
      throw XDRErrors.unknownEnumCase
    }
  }
}
