// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: ManageCreatePollRequestOp is used to create or remove a `CREATE_POLL` request
//  struct ManageCreatePollRequestOp
//  {
//      //: data is used to pass one of `ManageCreatePollRequestAction` with required params
//      union switch (ManageCreatePollRequestAction action)
//      {
//      case CREATE:
//          CreatePollRequestData createData;
//      case CANCEL:
//          CancelPollRequestData cancelData;
//      }
//      data;
//  
//      //: reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct ManageCreatePollRequestOp: XDREncodable {
  public var data: ManageCreatePollRequestOpData
  public var ext: ManageCreatePollRequestOpExt

  public init(
      data: ManageCreatePollRequestOpData,
      ext: ManageCreatePollRequestOpExt) {

    self.data = data
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.data.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum ManageCreatePollRequestOpData: XDRDiscriminatedUnion {
    case create(CreatePollRequestData)
    case cancel(CancelPollRequestData)

    public var discriminant: Int32 {
      switch self {
      case .create: return ManageCreatePollRequestAction.create.rawValue
      case .cancel: return ManageCreatePollRequestAction.cancel.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .create(let data): xdr.append(data.toXDR())
      case .cancel(let data): xdr.append(data.toXDR())
      }

      return xdr
    }

  }
  public enum ManageCreatePollRequestOpExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
