// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Actions that can be performed on balances
//  enum ManageBalanceAction
//  {
//      //: Create new balance
//      CREATE = 0,
//      //: Delete existing balance by ID. Is reserved and not implemented yet.
//      DELETE_BALANCE = 1,
//      //: Ensures that the balance will not be created if the balance of the provided asset exists and is attached to the provided account
//      CREATE_UNIQUE = 2
//  };

//  ===========================================================================
public enum ManageBalanceAction: Int32, XDREnum {
  case create = 0
  case deleteBalance = 1
  case createUnique = 2
}
