// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum ManageSignerRoleResultCode
//  {
//      //: Means that specified action in `data` of ManageSignerRoleOp was successfully executed
//      SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      //: There is no signer role with such id or source cannot manage the role
//      NOT_FOUND = -1, // does not exists or owner mismatched
//      //: Not allowed to remove role if it is attached at least to one singer
//      ROLE_IS_USED = -2,
//      //: Passed details has invalid json structure
//      INVALID_DETAILS = -3,
//      //: There is no rule with id passed through `ruleIDs`
//      NO_SUCH_RULE = -4,
//      //: Not allowed to duplicate ids in `ruleIDs` array
//      RULE_ID_DUPLICATION = -5,
//      //: Not allowed to pass ids of default rules on `ruleIDs` array
//      DEFAULT_RULE_ID_DUPLICATION = -6,
//      //: Not allowed to pass ruleIDs more than maxSignerRuleCount (by default 128)
//      TOO_MANY_RULE_IDS = -7
//  };

//  ===========================================================================
public enum ManageSignerRoleResultCode: Int32, XDREnum {
  case success = 0
  case notFound = -1
  case roleIsUsed = -2
  case invalidDetails = -3
  case noSuchRule = -4
  case ruleIdDuplication = -5
  case defaultRuleIdDuplication = -6
  case tooManyRuleIds = -7
}
