// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Actions that can be performed with an external system account ID in the external system ID pool
//  enum ManageExternalSystemAccountIdPoolEntryAction
//  {
//      CREATE = 0,
//      REMOVE = 1
//  };

//  ===========================================================================
public enum ManageExternalSystemAccountIdPoolEntryAction: Int32, XDREnum {
  case create = 0
  case remove = 1
}
