// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum OpenSwapResultCode
//  {
//      //: OpenSwap was successful 
//      SUCCESS = 0,
//  
//      //: Source and destination balances are the same
//      MALFORMED = -1,
//      //: Not enough funds in the source account
//      UNDERFUNDED = -2,
//      //: There is no balance found with an ID provided in `destinations.balanceID`
//      //: Sender balance asset and receiver balance asset are not equal
//      BALANCE_ASSETS_MISMATCHED = -3,
//      //: There is no balance found with ID provided in `sourceBalanceID`
//      SRC_BALANCE_NOT_FOUND = -4,
//      //: Payment asset does not have a `SWAPPABLE` policy set
//      NOT_ALLOWED_BY_ASSET_POLICY = -5,
//      //: Overflow during total fee calculation
//      INVALID_DESTINATION_FEE = -6,
//      //: Payment fee amount is insufficient
//      INSUFFICIENT_FEE_AMOUNT = -7,
//      //: Fee charged from destination balance is greater than the amount
//      AMOUNT_IS_LESS_THAN_DEST_FEE = -8,
//      //: There is no account found with an ID provided in `destination.accountID`
//      //: Amount precision and asset precision are mismatched
//      INCORRECT_AMOUNT_PRECISION = -9,
//      //: Not allowed to create swap with invalid json details
//      INVALID_DETAILS = -10,
//      //: Lock time is in the past
//      INVALID_LOCK_TIME = -11,
//      //: Zero amount is not allowed
//      INVALID_AMOUNT = -12
//  
//  };

//  ===========================================================================
public enum OpenSwapResultCode: Int32, XDREnum {
  case success = 0
  case malformed = -1
  case underfunded = -2
  case balanceAssetsMismatched = -3
  case srcBalanceNotFound = -4
  case notAllowedByAssetPolicy = -5
  case invalidDestinationFee = -6
  case insufficientFeeAmount = -7
  case amountIsLessThanDestFee = -8
  case incorrectAmountPrecision = -9
  case invalidDetails = -10
  case invalidLockTime = -11
  case invalidAmount = -12
}
