// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct OperationMeta
//  {
//      LedgerEntryChanges changes;
//  };

//  ===========================================================================
public struct OperationMeta: XDREncodable {
  public var changes: LedgerEntryChanges

  public init(
      changes: LedgerEntryChanges) {

    self.changes = changes
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.changes.toXDR())

    return xdr
  }
}
