// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  union PayoutResult switch (PayoutResultCode code)
//  {
//      case SUCCESS:
//          PayoutSuccessResult success;
//      default:
//          void;
//  };

//  ===========================================================================
public enum PayoutResult: XDRDiscriminatedUnion {
  case success(PayoutSuccessResult)

  public var discriminant: Int32 {
    switch self {
    case .success: return PayoutResultCode.success.rawValue
    }
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.discriminant.toXDR())

    switch self {
    case .success(let data): xdr.append(data.toXDR())
    }

    return xdr
  }

  public init(xdrData: inout Data) throws {
    let discriminant = try Int32(xdrData: &xdrData)

    switch discriminant {
    case PayoutResultCode.success.rawValue:
      let data = try PayoutSuccessResult(xdrData: &xdrData)
      self = .success(data)
    default:
      throw XDRErrors.unknownEnumCase
    }
  }
}
