// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum PayoutResultCode
//  {
//      // codes considered as "success" for the operation
//      SUCCESS = 0,    // payout successfully completed
//  
//      // codes considered as "failure" for the operation
//      INVALID_AMOUNT = -1, // max payout amount can not be zero
//      INVALID_ASSET = -2,
//      ASSET_NOT_FOUND = -3,
//      ASSET_NOT_TRANSFERABLE = -4, // asset must have policy transferable
//      BALANCE_NOT_FOUND = -5,
//      INSUFFICIENT_FEE_AMOUNT = -6,
//      FEE_EXCEEDS_ACTUAL_AMOUNT = -7,
//      TOTAL_FEE_OVERFLOW = -8,
//      UNDERFUNDED = -9, // not enough amount on source balance
//      HOLDERS_NOT_FOUND = -10, // there is no holders of such asset
//      MIN_AMOUNT_TOO_BIG = -11, // there is no appropriate holders balances
//      LINE_FULL = -12, // destination balance amount overflows
//      STATS_OVERFLOW = -13, // source statistics overflow
//      LIMITS_EXCEEDED = -14, // source account limit exceeded
//      INCORRECT_PRECISION = -15 // asset does not allow amounts with such precision
//  };

//  ===========================================================================
public enum PayoutResultCode: Int32, XDREnum {
  case success = 0
  case invalidAmount = -1
  case invalidAsset = -2
  case assetNotFound = -3
  case assetNotTransferable = -4
  case balanceNotFound = -5
  case insufficientFeeAmount = -6
  case feeExceedsActualAmount = -7
  case totalFeeOverflow = -8
  case underfunded = -9
  case holdersNotFound = -10
  case minAmountTooBig = -11
  case lineFull = -12
  case statsOverflow = -13
  case limitsExceeded = -14
  case incorrectPrecision = -15
}
