// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct PendingStatisticsEntry
//  {
//      uint64 statisticsID;
//      uint64 requestID;
//      uint64 amount;
//  
//      // reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public struct PendingStatisticsEntry: XDRCodable {
  public var statisticsID: Uint64
  public var requestID: Uint64
  public var amount: Uint64
  public var ext: PendingStatisticsEntryExt

  public init(
      statisticsID: Uint64,
      requestID: Uint64,
      amount: Uint64,
      ext: PendingStatisticsEntryExt) {

    self.statisticsID = statisticsID
    self.requestID = requestID
    self.amount = amount
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.statisticsID.toXDR())
    xdr.append(self.requestID.toXDR())
    xdr.append(self.amount.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.statisticsID = try Uint64(xdrData: &xdrData)
    self.requestID = try Uint64(xdrData: &xdrData)
    self.amount = try Uint64(xdrData: &xdrData)
    self.ext = try PendingStatisticsEntryExt(xdrData: &xdrData)
  }

  public enum PendingStatisticsEntryExt: XDRDiscriminatedUnion {
    case emptyVersion

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion: xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
