// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: PollResult is used to specify result of voting
//  enum PollResult
//  {
//      PASSED = 0,
//      FAILED = 1
//  };

//  ===========================================================================
public enum PollResult: Int32, XDREnum {
  case passed = 0
  case failed = 1
}
