// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: Result codes for `RemoveAssetPairOp`
//  enum RemoveAssetPairResultCode
//  {
//      //: Operation is successfully applied
//      SUCCESS = 0,
//      //: Asset pair not found
//      NOT_FOUND = -1,
//      //: Asset pair can't be deleted as it has active orders
//      HAS_ACTIVE_OFFERS = -2,
//      //: Asset pair can't be deleted as it has active sales
//      HAS_ACTIVE_SALES = -3,
//      //: Base or Quote asset is invalid
//      INVALID_ASSET_CODE = -4
//  };

//  ===========================================================================
public enum RemoveAssetPairResultCode: Int32, XDREnum {
  case success = 0
  case notFound = -1
  case hasActiveOffers = -2
  case hasActiveSales = -3
  case invalidAssetCode = -4
}
