// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: RemoveAccountRuleData is used to pass necessary params to remove existing account rule
//  struct RemoveAccountRuleData
//  {
//      //: Identifier of existing account rule
//      uint64 ruleID;
//  
//      //: reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct RemoveAccountRuleData: XDRCodable {
  public var ruleID: Uint64
  public var ext: RemoveAccountRuleDataExt

  public init(
      ruleID: Uint64,
      ext: RemoveAccountRuleDataExt) {

    self.ruleID = ruleID
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.ruleID.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.ruleID = try Uint64(xdrData: &xdrData)
    self.ext = try RemoveAccountRuleDataExt(xdrData: &xdrData)
  }

  public enum RemoveAccountRuleDataExt: XDRDiscriminatedUnion {
    case emptyVersion

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion: xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
