// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum ReviewableRequestType
//  {
//  	NONE = 0, // use this request type in ReviewRequestOp extended result if additional info is not required
//  	ANY = 1,
//  	CREATE_PRE_ISSUANCE = 2,
//  	CREATE_ISSUANCE = 3,
//  	CREATE_WITHDRAW = 4,
//  	CREATE_SALE = 5,
//  	UPDATE_LIMITS = 6,
//      CREATE_AML_ALERT = 7,
//  	CHANGE_ROLE = 8,
//  	UPDATE_SALE_DETAILS = 9,
//  	CREATE_ASSET = 10,
//  	CREATE_INVOICE = 11,
//  	MANAGE_CONTRACT = 12,
//  	UPDATE_ASSET = 13,
//  	CREATE_POLL = 14,
//  	CREATE_ATOMIC_SWAP_ASK = 16,
//  	CREATE_ATOMIC_SWAP_BID = 17,
//  	KYC_RECOVERY = 18,
//  	MANAGE_OFFER = 19,
//  	CREATE_PAYMENT = 20,
//  	PERFORM_REDEMPTION = 21
//  };

//  ===========================================================================
public enum ReviewableRequestType: Int32, XDREnum {
  case none = 0
  case any = 1
  case createPreIssuance = 2
  case createIssuance = 3
  case createWithdraw = 4
  case createSale = 5
  case updateLimits = 6
  case createAmlAlert = 7
  case changeRole = 8
  case updateSaleDetails = 9
  case createAsset = 10
  case createInvoice = 11
  case manageContract = 12
  case updateAsset = 13
  case createPoll = 14
  case createAtomicSwapAsk = 16
  case createAtomicSwapBid = 17
  case kycRecovery = 18
  case manageOffer = 19
  case createPayment = 20
  case performRedemption = 21
}
