// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct SCPBallot
//  {
//      uint32 counter; // n
//      Value value;    // x
//  };

//  ===========================================================================
public struct SCPBallot: XDRCodable {
  public var counter: Uint32
  public var value: Value

  public init(
      counter: Uint32,
      value: Value) {

    self.counter = counter
    self.value = value
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.counter.toXDR())
    xdr.append(self.value.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.counter = try Uint32(xdrData: &xdrData)
    self.value = try Value(xdrData: &xdrData)
  }
}
