// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  enum SignerRuleAction
//  {
//      ANY = 1,
//      CREATE = 2,
//      CREATE_FOR_OTHER = 3,
//      UPDATE = 4,
//      MANAGE = 5,
//      SEND = 6,
//      REMOVE = 7,
//      CANCEL = 8,
//      REVIEW = 9,
//      RECEIVE_ATOMIC_SWAP = 10,
//      PARTICIPATE = 11,
//      BIND = 12,
//      UPDATE_MAX_ISSUANCE = 13,
//      CHECK = 14
//  };

//  ===========================================================================
public enum SignerRuleAction: Int32, XDREnum {
  case any = 1
  case create = 2
  case createForOther = 3
  case update = 4
  case manage = 5
  case send = 6
  case remove = 7
  case cancel = 8
  case review = 9
  case receiveAtomicSwap = 10
  case participate = 11
  case bind = 12
  case updateMaxIssuance = 13
  case check = 14
}
