// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct UpdateAccountRuleData
//  {
//      //: Identifier of existing signer rule
//      uint64 ruleID;
//      //: Resource is used to specify entity (for some - with properties) that can be managed through operations
//      AccountRuleResource resource;
//      //: Value from enum that can be applied to `resource`
//      AccountRuleAction action;
//      //: True if such `action` on such `resource` is prohibited, otherwise allows
//      bool forbids;
//      //: Arbitrary stringified json object that will be attached to rule
//      longstring details;
//  
//      //: reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct UpdateAccountRuleData: XDREncodable {
  public var ruleID: Uint64
  public var resource: AccountRuleResource
  public var action: AccountRuleAction
  public var forbids: Bool
  public var details: Longstring
  public var ext: UpdateAccountRuleDataExt

  public init(
      ruleID: Uint64,
      resource: AccountRuleResource,
      action: AccountRuleAction,
      forbids: Bool,
      details: Longstring,
      ext: UpdateAccountRuleDataExt) {

    self.ruleID = ruleID
    self.resource = resource
    self.action = action
    self.forbids = forbids
    self.details = details
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.ruleID.toXDR())
    xdr.append(self.resource.toXDR())
    xdr.append(self.action.toXDR())
    xdr.append(self.forbids.toXDR())
    xdr.append(self.details.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public enum UpdateAccountRuleDataExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

  }
}
