// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  struct UpdateDataOp
//  {
//      //: ID of the data entry to update
//      uint64 dataID;
//      //: New value to set
//      longstring value;
//      //: Reserved for future extension
//      EmptyExt ext;
//  };

//  ===========================================================================
public struct UpdateDataOp: XDRCodable {
  public var dataID: Uint64
  public var value: Longstring
  public var ext: EmptyExt

  public init(
      dataID: Uint64,
      value: Longstring,
      ext: EmptyExt) {

    self.dataID = dataID
    self.value = value
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.dataID.toXDR())
    xdr.append(self.value.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.dataID = try Uint64(xdrData: &xdrData)
    self.value = try Longstring(xdrData: &xdrData)
    self.ext = try EmptyExt(xdrData: &xdrData)
  }
}
