// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

import Foundation

// === xdr source ============================================================

//  //: UpdateSignerRoleData is used to pass necessary params to update an existing signer role
//  struct UpdateSignerRoleData
//  {
//      //: ID of an existing signer role
//      uint64 roleID;
//      //: Array of ids of existing, unique and not default rules
//      uint64 ruleIDs<>;
//  
//      //: Arbitrary stringified json object with details to attach to the role
//      longstring details;
//  
//      //: reserved for future use
//      union switch (LedgerVersion v)
//      {
//      case EMPTY_VERSION:
//          void;
//      } ext;
//  };

//  ===========================================================================
public struct UpdateSignerRoleData: XDRCodable {
  public var roleID: Uint64
  public var ruleIDs: [Uint64]
  public var details: Longstring
  public var ext: UpdateSignerRoleDataExt

  public init(
      roleID: Uint64,
      ruleIDs: [Uint64],
      details: Longstring,
      ext: UpdateSignerRoleDataExt) {

    self.roleID = roleID
    self.ruleIDs = ruleIDs
    self.details = details
    self.ext = ext
  }

  public func toXDR() -> Data {
    var xdr = Data()

    xdr.append(self.roleID.toXDR())
    xdr.append(self.ruleIDs.toXDR())
    xdr.append(self.details.toXDR())
    xdr.append(self.ext.toXDR())

    return xdr
  }

  public init(xdrData: inout Data) throws {
    self.roleID = try Uint64(xdrData: &xdrData)
    let lengthruleIDs = try Int32(xdrData: &xdrData)
    self.ruleIDs = [Uint64]()
    for _ in 1...lengthruleIDs {
      self.ruleIDs.append(try Uint64(xdrData: &xdrData))
    }
    self.details = try Longstring(xdrData: &xdrData)
    self.ext = try UpdateSignerRoleDataExt(xdrData: &xdrData)
  }

  public enum UpdateSignerRoleDataExt: XDRDiscriminatedUnion {
    case emptyVersion()

    public var discriminant: Int32 {
      switch self {
      case .emptyVersion: return LedgerVersion.emptyVersion.rawValue
      }
    }

    public func toXDR() -> Data {
      var xdr = Data()

      xdr.append(self.discriminant.toXDR())

      switch self {
      case .emptyVersion(): xdr.append(Data())
      }

      return xdr
    }

    public init(xdrData: inout Data) throws {
      let discriminant = try Int32(xdrData: &xdrData)

      switch discriminant {
      case LedgerVersion.emptyVersion.rawValue: self = .emptyVersion()
      default:
        throw XDRErrors.unknownEnumCase
      }
    }

  }
}
