// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

import Foundation

/// Fixed length byte array 
public struct XDRDataFixed32: XDRDataFixed {
  public static var length: Int { return 32 }

  public var wrapped: Data

  public init() {
      self.wrapped = Data()
  }
}
